# Generated by Django 4.1.6 on 2023-03-08 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0002_documentales'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
