# Generated by Django 4.1.6 on 2023-03-08 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0003_capitulo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentales',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='documentales',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='documentales',
            name='temporada',
        ),
        migrations.AddField(
            model_name='documentales',
            name='descargada',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='documentales',
            name='maker',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentales',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
