# Generated by Django 4.1.6 on 2023-03-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0004_remove_documentales_numero_remove_documentales_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
