# Generated by Django 4.1.6 on 2023-03-12 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mispeliculas', '0006_capitulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='reseña',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
