# Generated by Django 4.1.6 on 2023-03-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0007_capitulo_user_pelicula_user_serie_fecha_serie_reseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='reseña',
            field=models.TextField(blank=True),
        ),
    ]
